coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        flags:
          - php
    patch:
      default:
        target: auto
        threshold: 1%
        flags:
          - php

comment: false
